// experiments/02-react-shadcn/src/App.tsx
import { useEffect, useLayoutEffect, useState } from 'react'
import { layout, normalizeRecipe, type GridPlan, type Recipe } from '@recipe/core'
import { Chart } from './Chart'

const RECIPES = [
  'espresso-brownies',
  'no-knead-bread',
  'shepherds-pie',
  'beef-stroganoff',
  'grilled-artichokes',
  'spinach-artichoke-skillet',
  'braised-short-ribs',
  'fennel-citrus-salad',
  'bbq-pulled-chicken',
]

const FIXTURES = [
  'long-text',
  'unicode',
  'wide-shallow',
  'deep-narrow',
  'reuse-split',
  'degenerate',
]

const SCALES = [
  ['0.5', 'half'],
  ['1', 'as written'],
  ['2', 'double'],
  ['3', 'triple'],
] as const

type Loaded = { slug: string; recipe: Recipe; plans: GridPlan[] }

/**
 * The corpus is fetched at runtime rather than bundled.
 *
 * Every track loads the same JSON over the same static server, so Phase 08's bundle numbers
 * measure the renderer rather than how much of the corpus each track happened to inline.
 */
async function load(slug: string): Promise<Loaded> {
  const response = await fetch(`/packages/corpus/${slug}.json`)
  if (!response.ok) throw new Error(`${slug} → ${response.status}`)
  const recipe = normalizeRecipe(await response.json())
  return { slug, recipe, plans: recipe.components.map((c) => layout(c)) }
}

export function App() {
  const [slug, setSlug] = useState('recipes/espresso-brownies')
  const [loaded, setLoaded] = useState<Loaded | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [scale, setScale] = useState(1)
  const [checked, setChecked] = useState<ReadonlySet<string>>(new Set())
  // Seeded in `main.tsx` from the OS preference, so a control that read "light" on a dark page
  // would be worse than no control.
  const [theme, setTheme] = useState(
    () => document.documentElement.getAttribute('data-theme') ?? 'light',
  )

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  useEffect(() => {
    let live = true
    // The same stale-response guard track 01 needed: a slow fetch must not overwrite a newer one.
    load(slug)
      .then((next) => live && (setLoaded(next), setChecked(new Set()), setError(null)))
      .catch((cause) => live && setError(cause as Error))
    return () => {
      live = false
    }
  }, [slug])

  const toggle = (key: string) =>
    setChecked((current) => {
      const next = new Set(current)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })

  const toggleMeasured = (key: string) => {
    performance.mark('recipe:check-off:start')
    toggle(key)
  }

  if (error) {
    return (
      <pre className="m-4 rounded-sm bg-clay-soft p-4 font-mono text-label whitespace-pre-wrap">
        {error.stack ?? error.message}
      </pre>
    )
  }

  return (
    <main className="mx-auto flex max-w-[1400px] flex-col gap-4 p-4">
      <div
        data-controls
        className="sticky top-0 z-10 flex flex-wrap items-center gap-x-5 gap-y-2 rounded border border-hairline bg-surface px-3.5 py-3 font-mono text-label"
      >
        <label className="flex cursor-pointer items-center gap-1.5">
          recipe
          <select
            id="recipe"
            className="font-inherit px-1 py-0.5"
            value={slug}
            onChange={(e) => setSlug(e.target.value)}
          >
            <optgroup label="recipes">
              {RECIPES.map((name) => (
                <option key={name} value={`recipes/${name}`}>
                  {name}
                </option>
              ))}
            </optgroup>
            <optgroup label="fixtures">
              {FIXTURES.map((name) => (
                <option key={name} value={`fixtures/valid/${name}`}>
                  {name}
                </option>
              ))}
            </optgroup>
          </select>
        </label>

        <label className="flex cursor-pointer items-center gap-1.5">
          servings
          <select
            id="scale"
            className="font-inherit px-1 py-0.5"
            value={String(scale)}
            onChange={(e) => {
              // Phase 08's sharpest discriminator between reactivity models: one change that
              // touches every quantity cell at once.
              performance.mark('recipe:render:start')
              setScale(Number(e.target.value))
            }}
          >
            {SCALES.map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
        </label>

        <label className="flex cursor-pointer items-center gap-1.5">
          theme
          <select
            id="theme"
            className="font-inherit px-1 py-0.5"
            value={theme}
            onChange={(e) => setTheme(e.target.value)}
          >
            <option value="light">light</option>
            <option value="dark">dark</option>
          </select>
        </label>
      </div>

      {loaded && <Card loaded={loaded} scale={scale} checked={checked} onToggle={toggleMeasured} />}
    </main>
  )
}

function Card({
  loaded,
  scale,
  checked,
  onToggle,
}: {
  loaded: Loaded
  scale: number
  checked: ReadonlySet<string>
  onToggle: (key: string) => void
}) {
  const { recipe, plans, slug } = loaded

  /**
   * The harness marks, emitted from a layout effect so "painted" means the DOM is committed
   * rather than the render function having returned.
   *
   * Plain `performance.mark` by convention — a track that imports the harness is measuring
   * itself, and dependency-cruiser enforces it. See `packages/harness/src/protocol.ts`.
   */
  useLayoutEffect(() => {
    performance.mark('recipe:render:end')
    const first = performance.getEntriesByName('recipe:first-render').length === 0
    try {
      performance.measure(
        first ? 'recipe:first-render' : 'recipe:render',
        'recipe:render:start',
        'recipe:render:end',
      )
    } catch {
      // The start mark is set by `main.tsx` before the first paint and by the change handlers
      // after; a render with neither is not one Phase 08 is asking about.
    }
    if (performance.getEntriesByName('recipe:check-off:start').length > 0) {
      performance.measure('recipe:check-off', 'recipe:check-off:start', 'recipe:render:end')
      performance.clearMarks('recipe:check-off:start')
    }
    document.title = `${recipe.title} — track 02`
  })

  return (
    <article className="overflow-hidden rounded border border-hairline bg-surface" data-card>
      <header className="border-b border-hairline px-4 pt-4 pb-3">
        <h2 className="font-display text-card-title font-semibold">{recipe.title}</h2>
        {recipe.source && (
          <p className="mt-1 font-mono text-label text-ink-faint">{recipe.source.name}</p>
        )}
      </header>

      <div data-recipe={slug}>
        {recipe.components.map((component, i) => (
          <section key={component.id}>
            {recipe.components.length > 1 && component.title && (
              <h3 className="mt-3.5 mb-1 px-4 font-display text-component-title font-semibold">
                {component.title}
              </h3>
            )}
            <Chart
              component={component}
              plan={plans[i]!}
              scale={scale}
              checked={checked}
              onToggle={onToggle}
            />
          </section>
        ))}
      </div>
    </article>
  )
}

// experiments/04-alt-frameworks/src/svelte/App.svelte
<script>
  import { FIXTURES, RECIPES, SCALES, load, markEnd, markStart } from '../shared.js'
  import Chart from './Chart.svelte'

  /**
   * Svelte 5 runes. `$state` for what changes, `$derived` for what follows from it, `$effect` for
   * the two things that reach outside the component — loading and the harness mark.
   *
   * The scaling interaction is the measurement PHASE-07 cares most about: changing `scale` has to
   * reach every quantity cell at once, and how much work that costs is the framework difference
   * the whole track exists to isolate.
   */
  let slug = $state('recipes/espresso-brownies')
  let loaded = $state(null)
  let error = $state(null)
  let scale = $state(1)
  // A new Set on every toggle rather than mutation. Runes track reassignment, and this keeps the
  // update shape identical to the Solid and React variants so the comparison is about the
  // framework rather than about who mutated in place.
  let checked = $state(new Set())
  let theme = $state(document.documentElement.getAttribute('data-theme') ?? 'light')

  $effect(() => {
    const wanted = slug
    let live = true
    load(wanted)
      .then((next) => {
        // The same stale-response guard every track needed: a slow fetch must not overwrite a
        // newer one.
        if (!live) return
        loaded = next
        checked = new Set()
        error = null
      })
      .catch((cause) => live && (error = cause))
    return () => {
      live = false
    }
  })

  $effect(() => {
    document.documentElement.setAttribute('data-theme', theme)
  })

  $effect(() => {
    if (!loaded) return
    document.title = `${loaded.recipe.title} — track 04 svelte`
    markEnd()
  })

  function toggle(key) {
    const next = new Set(checked)
    if (next.has(key)) next.delete(key)
    else next.add(key)
    checked = next
  }
</script>

<main class="page">
  <div class="controls" data-controls>
    <label>
      recipe
      <select id="recipe" bind:value={slug} onchange={markStart}>
        <optgroup label="recipes">
          {#each RECIPES as name (name)}<option value="recipes/{name}">{name}</option>{/each}
        </optgroup>
        <optgroup label="fixtures">
          {#each FIXTURES as name (name)}
            <option value="fixtures/valid/{name}">{name}</option>
          {/each}
        </optgroup>
      </select>
    </label>

    <label>
      servings
      <select
        id="scale"
        value={String(scale)}
        onchange={(e) => {
          markStart()
          scale = Number(e.currentTarget.value)
        }}
      >
        {#each SCALES as [value, label] (value)}<option {value}>{label}</option>{/each}
      </select>
    </label>

    <label>
      theme
      <select id="theme" bind:value={theme}>
        <option value="light">light</option>
        <option value="dark">dark</option>
      </select>
    </label>
  </div>

  {#if error}
    <pre class="failure">{error.stack ?? error.message}</pre>
  {:else if loaded}
    <article class="card" data-card>
      <header class="cardhead">
        <h2 class="card-title">{loaded.recipe.title}</h2>
        {#if loaded.recipe.source}<p class="src">{loaded.recipe.source.name}</p>{/if}
      </header>
      <div data-recipe={loaded.slug}>
        {#each loaded.recipe.components as component, i (component.id)}
          <section>
            {#if loaded.recipe.components.length > 1 && component.title}
              <h3 class="component-title">{component.title}</h3>
            {/if}
            <Chart {component} plan={loaded.plans[i]} {scale} {checked} onToggle={toggle} />
          </section>
        {/each}
      </div>
    </article>
  {/if}
</main>
